/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mallas.interfaz;

import com.mallas.entidades.EntUsuario;
import com.mallas.negocio.UsuarioNegocio;
import com.mallas.persistencia.DaosUsuario;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author samsung
 */
public class ConfiguracionCuentaE extends javax.swing.JFrame {

    /**
     * Creates new form ConfiguracionCuenta
     */
    static EntUsuario userE;
    UsuarioNegocio userN = new UsuarioNegocio();
    
    

    public ConfiguracionCuentaE() throws Exception {
        userE = userN.configUser();
        initComponents();
        super.setLocationRelativeTo(null); 
        setIconImage(new ImageIcon(getClass().getResource("/com/mallas/imagenes/Desktop Icon.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabelInsumos3 = new javax.swing.JLabel();
        jLabelClientes3 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabelObras3 = new javax.swing.JLabel();
        jLabelProveedores3 = new javax.swing.JLabel();
        jLabelProductos3 = new javax.swing.JLabel();
        jLabelCloseSesion3 = new javax.swing.JLabel();
        jLabelSettings = new javax.swing.JLabel();
        jLabelMenuPrincipal3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtClave = new javax.swing.JPasswordField();
        txtDNI = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cboPerfil = new javax.swing.JComboBox();
        txtCorreo = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cboEstado = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabelEditar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel7.setBackground(new java.awt.Color(8, 102, 198));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mallas/imagenes/logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(40, 40, 40));

        jLabelInsumos3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelInsumos3.setForeground(new java.awt.Color(204, 204, 204));
        jLabelInsumos3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelInsumos3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mallas/imagenes/InsumosIcon.png"))); // NOI18N
        jLabelInsumos3.setText("Insumos");
        jLabelInsumos3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jLabelInsumos3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelInsumos3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelInsumos3MouseClicked(evt);
            }
        });

        jLabelClientes3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelClientes3.setForeground(new java.awt.Color(204, 204, 204));
        jLabelClientes3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelClientes3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mallas/imagenes/ClientesIcon.png"))); // NOI18N
        jLabelClientes3.setText("Clientes");
        jLabelClientes3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jLabelClientes3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClientes3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelClientes3MouseClicked(evt);
            }
        });

        jLabel17.setBackground(new java.awt.Color(35, 35, 35));
        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Navegación");
        jLabel17.setOpaque(true);

        jLabelObras3.setBackground(new java.awt.Color(51, 51, 51));
        jLabelObras3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelObras3.setForeground(new java.awt.Color(204, 204, 204));
        jLabelObras3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelObras3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mallas/imagenes/ObrasIcon.png"))); // NOI18N
        jLabelObras3.setText("Obras");
        jLabelObras3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jLabelObras3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelObras3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelObras3MouseClicked(evt);
            }
        });

        jLabelProveedores3.setBackground(new java.awt.Color(51, 51, 51));
        jLabelProveedores3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelProveedores3.setForeground(new java.awt.Color(204, 204, 204));
        jLabelProveedores3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProveedores3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mallas/imagenes/ProveedoresIcon.png"))); // NOI18N
        jLabelProveedores3.setText("Proveedores");
        jLabelProveedores3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jLabelProveedores3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelProveedores3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelProveedores3MouseClicked(evt);
            }
        });

        jLabelProductos3.setBackground(new java.awt.Color(51, 51, 51));
        jLabelProductos3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelProductos3.setForeground(new java.awt.Color(204, 204, 204));
        jLabelProductos3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProductos3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mallas/imagenes/ProductosIcon.png"))); // NOI18N
        jLabelProductos3.setText("Productos");
        jLabelProductos3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jLabelProductos3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelProductos3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelProductos3MouseClicked(evt);
            }
        });

        jLabelCloseSesion3.setBackground(new java.awt.Color(51, 51, 51));
        jLabelCloseSesion3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelCloseSesion3.setForeground(new java.awt.Color(204, 204, 204));
        jLabelCloseSesion3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCloseSesion3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mallas/imagenes/CerrarSesion.png"))); // NOI18N
        jLabelCloseSesion3.setText("Cerrar Sesión");
        jLabelCloseSesion3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jLabelCloseSesion3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelCloseSesion3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseSesion3MouseClicked(evt);
            }
        });

        jLabelSettings.setBackground(new java.awt.Color(51, 51, 51));
        jLabelSettings.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelSettings.setForeground(new java.awt.Color(204, 204, 204));
        jLabelSettings.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mallas/imagenes/SettingsIcon.png"))); // NOI18N
        jLabelSettings.setText("Configuración de cuenta");
        jLabelSettings.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jLabelSettings.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelSettings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSettingsMouseClicked(evt);
            }
        });

        jLabelMenuPrincipal3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelMenuPrincipal3.setForeground(new java.awt.Color(204, 204, 204));
        jLabelMenuPrincipal3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMenuPrincipal3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mallas/imagenes/Home.png"))); // NOI18N
        jLabelMenuPrincipal3.setText("Menú Principal");
        jLabelMenuPrincipal3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jLabelMenuPrincipal3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMenuPrincipal3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabelMenuPrincipal3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMenuPrincipal3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelInsumos3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelClientes3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelObras3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelProveedores3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelProductos3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelSettings, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
            .addComponent(jLabelCloseSesion3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelMenuPrincipal3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(jLabelMenuPrincipal3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelInsumos3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelClientes3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelObras3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelProveedores3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelProductos3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCloseSesion3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(40, 40, 40)));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("* Apellido:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Correo:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("* DNI:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("* Nombre:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("* Perfil:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("* Estado:");

        txtClave.setText(userE.getClave());

        txtDNI.setText(Integer.toString(userE.getDNI()));
        txtDNI.setEnabled(false);

        txtUsuario.setText(userE.usuario);
        txtUsuario.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("* Clave:");

        cboPerfil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Administrador", "Empleado" }));
        cboPerfil.setSelectedItem(userE.getRol());
        cboPerfil.setEnabled(false);

        txtCorreo.setText(userE.getCorreo());
        txtCorreo.setToolTipText("");

        txtApellido.setText(userE.getApellido());
        txtApellido.setEnabled(false);

        txtNombre.setText(userE.getNombre());
        txtNombre.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("* Usuario:");

        cboEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Activo", "Inactivo" }));
        cboEstado.setSelectedItem(userE.getEstado());

        jPanel2.setBackground(new java.awt.Color(40, 40, 40));
        jPanel2.setPreferredSize(new java.awt.Dimension(500, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Administración de la cuenta");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap())
        );

        jLabelEditar.setBackground(new java.awt.Color(8, 102, 198));
        jLabelEditar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelEditar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEditar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEditar.setText("Editar");
        jLabelEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelEditar.setOpaque(true);
        jLabelEditar.setPreferredSize(new java.awt.Dimension(45, 16));
        jLabelEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelEditarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabelEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cboPerfil, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cboEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtClave, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(0, 297, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addGap(18, 18, 18)
                .addComponent(jLabelEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(195, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 11, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
      
    private void jLabelInsumos3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelInsumos3MouseClicked
        FInsumosE fIns = new FInsumosE();
        this.setVisible(false);
        fIns.setVisible(true);
    }//GEN-LAST:event_jLabelInsumos3MouseClicked

    private void jLabelClientes3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelClientes3MouseClicked
        FClientesE fCli = new FClientesE();
        this.setVisible(false);
        fCli.setVisible(true);
    }//GEN-LAST:event_jLabelClientes3MouseClicked

    private void jLabelObras3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelObras3MouseClicked
        FObrasE fObr = new FObrasE();
        this.setVisible(false);
        fObr.setVisible(true);
    }//GEN-LAST:event_jLabelObras3MouseClicked

    private void jLabelProveedores3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelProveedores3MouseClicked
        FProveedoresE fProv = new FProveedoresE();
        this.setVisible(false);
        fProv.setVisible(true);
    }//GEN-LAST:event_jLabelProveedores3MouseClicked

    private void jLabelProductos3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelProductos3MouseClicked
        FProductosE fPro = new FProductosE();
        this.setVisible(false);
        fPro.setVisible(true);
    }//GEN-LAST:event_jLabelProductos3MouseClicked

    private void jLabelCloseSesion3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseSesion3MouseClicked
        int confirmar = JOptionPane.showConfirmDialog(null, "¿Está seguro que desea cerrar la sesión?", "Salir", JOptionPane.YES_NO_OPTION);

        if (JOptionPane.YES_OPTION == confirmar) {
            try {
                InicioSesion is = new InicioSesion();
                this.dispose();
                is.setVisible(true);
            } catch (Exception ex) {
                Logger.getLogger(FUsuarios.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jLabelCloseSesion3MouseClicked

    private void jLabelEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEditarMouseClicked
        try {
            
            /**
             *Se realizan las validaciones de los campos de texto*/
            
            if (txtClave.getText().trim().length() > 0) {
                userE.setClave(txtClave.getText());
            } else {
                JOptionPane.showMessageDialog(null, "Por favor ingrese la Clave", "Datos Faltantes", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (txtClave.getText().trim().length() < 10) {
                JOptionPane.showMessageDialog(null, "La Clave debe ser mayor de 10 caracteres", "Datos Incompletos", JOptionPane.ERROR_MESSAGE);
            }

            userE.setRol(cboPerfil.getSelectedItem().toString());
            userE.setEstado(cboEstado.getSelectedItem().toString());

            if (txtCorreo.getText().trim() != null) {
                userE.setCorreo(txtCorreo.getText());
            } else {
                userE.setCorreo("Sin correo");
            }

            boolean respuesta = userN.actualizarUsuarioEnt(userE);
            
            /**
              *Se da respuesta*/
            
            if (respuesta == true) {
                JOptionPane.showMessageDialog(null, "Se ha actualizado satisfactoriamente", "Actualizar", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Hubo un error en el proceso de actualización del usuario", "Actualizar", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            Logger.getLogger(FUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabelEditarMouseClicked

    private void jLabelSettingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSettingsMouseClicked
        try {
            ConfiguracionCuentaE cc = new ConfiguracionCuentaE();
            this.setVisible(false);
            cc.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(ConfiguracionCuentaE.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabelSettingsMouseClicked

    private void jLabelMenuPrincipal3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMenuPrincipal3MouseClicked
        MenuPrincipalE mpe = new MenuPrincipalE();
        this.setVisible(false);
        mpe.setVisible(true);
    }//GEN-LAST:event_jLabelMenuPrincipal3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfiguracionCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfiguracionCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfiguracionCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfiguracionCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ConfiguracionCuentaE().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(ConfiguracionCuentaE.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cboEstado;
    private javax.swing.JComboBox cboPerfil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelClientes3;
    private javax.swing.JLabel jLabelCloseSesion3;
    private javax.swing.JLabel jLabelEditar;
    private javax.swing.JLabel jLabelInsumos3;
    private javax.swing.JLabel jLabelMenuPrincipal3;
    private javax.swing.JLabel jLabelObras3;
    private javax.swing.JLabel jLabelProductos3;
    private javax.swing.JLabel jLabelProveedores3;
    private javax.swing.JLabel jLabelSettings;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JPasswordField txtClave;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
