/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mallas.interfaz;

import com.mallas.entidades.EntClientes;
import com.mallas.negocio.ClienteNegocio;
import com.mallas.entidades.EntUsuario;
import com.mallas.negocio.UsuarioNegocio;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author samsung
 */
public class FClientesE extends javax.swing.JFrame {

    /**
     * Creates new form FProveedores
     */
    public FClientesE() {
        initComponents();
        super.setLocationRelativeTo(null);
        jLabelGuardar.setOpaque(true);
        jLabelActualizar.setOpaque(true);
        jLabelConsultar.setOpaque(true);
        jLabelEliminar.setOpaque(true);
        jLabelLimpiar.setOpaque(true);
        jLabelImprimir.setOpaque(true);
        jLabel8.setOpaque(true);
        setIconImage(new ImageIcon(getClass().getResource("/com/mallas/imagenes/Desktop Icon.png")).getImage());
    }
    ClienteNegocio provN = new ClienteNegocio();
    EntClientes provE = new EntClientes();

    UsuarioNegocio userN = new UsuarioNegocio();
    EntUsuario userE = new EntUsuario();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cboRegimen_Tributario = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNIT = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtRazon_Social = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtRepresentante_Legal = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabelGuardar = new javax.swing.JLabel();
        jLabelActualizar = new javax.swing.JLabel();
        jLabelConsultar = new javax.swing.JLabel();
        jLabelEliminar = new javax.swing.JLabel();
        jLabelLimpiar = new javax.swing.JLabel();
        jLabelImprimir = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabelInsumos = new javax.swing.JLabel();
        jLabelClientes = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabelObras = new javax.swing.JLabel();
        jLabelProveedores = new javax.swing.JLabel();
        jLabelProductos = new javax.swing.JLabel();
        jLabelCloseSesion = new javax.swing.JLabel();
        jLabelConfiguracion = new javax.swing.JLabel();
        jLabelMenuPrincipal3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cboRegimen_Tributario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Regimen Común", "Regimen Simplificado" }));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("* NIT/Cédula:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("* Razón Social:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("* Dirección:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("* Teléfono:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("* Representante Legal:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("* Régimen Tributario:");

        jPanel2.setBackground(new java.awt.Color(40, 40, 40));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Administración de Clientes");
        jLabel9.setMaximumSize(new java.awt.Dimension(174, 16));
        jLabel9.setMinimumSize(new java.awt.Dimension(174, 16));
        jLabel9.setPreferredSize(new java.awt.Dimension(174, 16));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabelGuardar.setBackground(new java.awt.Color(8, 102, 198));
        jLabelGuardar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelGuardar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGuardar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelGuardar.setText("Guardar");
        jLabelGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelGuardarMouseClicked(evt);
            }
        });

        jLabelActualizar.setBackground(new java.awt.Color(8, 102, 198));
        jLabelActualizar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelActualizar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelActualizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelActualizar.setText("Actualizar");
        jLabelActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelActualizarMouseClicked(evt);
            }
        });

        jLabelConsultar.setBackground(new java.awt.Color(8, 102, 198));
        jLabelConsultar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelConsultar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelConsultar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelConsultar.setText("Consultar");
        jLabelConsultar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelConsultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelConsultarMouseClicked(evt);
            }
        });

        jLabelEliminar.setBackground(new java.awt.Color(8, 102, 198));
        jLabelEliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelEliminar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEliminar.setText("Eliminar");
        jLabelEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelEliminarMouseClicked(evt);
            }
        });

        jLabelLimpiar.setBackground(new java.awt.Color(8, 102, 198));
        jLabelLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLimpiar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLimpiar.setText("Limpiar");
        jLabelLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLimpiarMouseClicked(evt);
            }
        });

        jLabelImprimir.setBackground(new java.awt.Color(8, 102, 198));
        jLabelImprimir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelImprimir.setForeground(new java.awt.Color(255, 255, 255));
        jLabelImprimir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelImprimir.setText("Imprimir");
        jLabelImprimir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelImprimir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelImprimirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addGap(24, 24, 24))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNIT)
                            .addComponent(txtRazon_Social)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cboRegimen_Tributario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtRepresentante_Legal)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jLabelConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jLabelEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRepresentante_Legal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboRegimen_Tributario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtNIT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRazon_Social, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)))
                    .addComponent(jLabel1))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(8, 102, 198));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mallas/imagenes/logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(11, 11, 11))
        );

        jPanel6.setBackground(new java.awt.Color(40, 40, 40));
        jPanel6.setPreferredSize(new java.awt.Dimension(272, 420));

        jLabelInsumos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelInsumos.setForeground(new java.awt.Color(204, 204, 204));
        jLabelInsumos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelInsumos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mallas/imagenes/InsumosIcon.png"))); // NOI18N
        jLabelInsumos.setText("Insumos");
        jLabelInsumos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jLabelInsumos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelInsumos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelInsumosMouseClicked(evt);
            }
        });

        jLabelClientes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelClientes.setForeground(new java.awt.Color(204, 204, 204));
        jLabelClientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mallas/imagenes/ClientesIcon.png"))); // NOI18N
        jLabelClientes.setText("Clientes");
        jLabelClientes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jLabelClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelClientesMouseClicked(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(35, 35, 35));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Navegación");
        jLabel8.setOpaque(true);

        jLabelObras.setBackground(new java.awt.Color(51, 51, 51));
        jLabelObras.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelObras.setForeground(new java.awt.Color(204, 204, 204));
        jLabelObras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelObras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mallas/imagenes/ObrasIcon.png"))); // NOI18N
        jLabelObras.setText("Obras");
        jLabelObras.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jLabelObras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelObras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelObrasMouseClicked(evt);
            }
        });

        jLabelProveedores.setBackground(new java.awt.Color(51, 51, 51));
        jLabelProveedores.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelProveedores.setForeground(new java.awt.Color(204, 204, 204));
        jLabelProveedores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mallas/imagenes/ProveedoresIcon.png"))); // NOI18N
        jLabelProveedores.setText("Proveedores");
        jLabelProveedores.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jLabelProveedores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelProveedoresMouseClicked(evt);
            }
        });

        jLabelProductos.setBackground(new java.awt.Color(51, 51, 51));
        jLabelProductos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelProductos.setForeground(new java.awt.Color(204, 204, 204));
        jLabelProductos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mallas/imagenes/ProductosIcon.png"))); // NOI18N
        jLabelProductos.setText("Productos");
        jLabelProductos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jLabelProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelProductosMouseClicked(evt);
            }
        });

        jLabelCloseSesion.setBackground(new java.awt.Color(51, 51, 51));
        jLabelCloseSesion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelCloseSesion.setForeground(new java.awt.Color(204, 204, 204));
        jLabelCloseSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCloseSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mallas/imagenes/CerrarSesion.png"))); // NOI18N
        jLabelCloseSesion.setText("Cerrar Sesión");
        jLabelCloseSesion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jLabelCloseSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelCloseSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseSesionMouseClicked(evt);
            }
        });

        jLabelConfiguracion.setBackground(new java.awt.Color(51, 51, 51));
        jLabelConfiguracion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelConfiguracion.setForeground(new java.awt.Color(204, 204, 204));
        jLabelConfiguracion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelConfiguracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mallas/imagenes/SettingsIcon.png"))); // NOI18N
        jLabelConfiguracion.setText("Configuración de cuenta");
        jLabelConfiguracion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jLabelConfiguracion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelConfiguracion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelConfiguracionMouseClicked(evt);
            }
        });

        jLabelMenuPrincipal3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelMenuPrincipal3.setForeground(new java.awt.Color(204, 204, 204));
        jLabelMenuPrincipal3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMenuPrincipal3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mallas/imagenes/Home.png"))); // NOI18N
        jLabelMenuPrincipal3.setText("Menú Principal");
        jLabelMenuPrincipal3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jLabelMenuPrincipal3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMenuPrincipal3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabelMenuPrincipal3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMenuPrincipal3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelInsumos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelClientes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelObras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelProveedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelCloseSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelConfiguracion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
            .addComponent(jLabelMenuPrincipal3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(jLabelMenuPrincipal3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelInsumos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelObras, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelConfiguracion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCloseSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelGuardarMouseClicked
        
        EntClientes cabeza = null;
        provE.setNext(cabeza);
        
        /**
         *Se realizan las validaciones de los campos de texto*/
        
        if (txtNIT.getText().trim().length() > 0) {
            provE.setNIT(txtNIT.getText());
        } else {
            JOptionPane.showMessageDialog(null, "Por favor ingrese el NIT o Cédula", "Datos Faltantes", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (txtRazon_Social.getText().trim().length() > 0) {
            provE.setRazon_social(txtRazon_Social.getText());
        } else {
            JOptionPane.showMessageDialog(null, "Por favor ingrese la Razón Social", "Datos Faltantes", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (txtDireccion.getText().trim().length() > 0) {
            provE.setDireccion(txtDireccion.getText());
        } else {
            JOptionPane.showMessageDialog(null, "Por favor ingrese la Dirección", "Datos Faltantes", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (txtTelefono.getText().trim().length() > 0) {
            provE.setTelefono(txtTelefono.getText());
        } else {
            JOptionPane.showMessageDialog(null, "Por favor ingrese el Teléfono", "Datos Faltantes", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (txtRepresentante_Legal.getText().trim().length() > 0) {
            provE.setRepresentante_legal(txtRepresentante_Legal.getText());
        } else {
            JOptionPane.showMessageDialog(null, "Por favor ingrese el Representante Legal", "Datos Faltantes", JOptionPane.ERROR_MESSAGE);
            return;
        }

        provE.setRegimen_tributario((String) cboRegimen_Tributario.getSelectedItem());

        boolean respuesta = provN.guardarCliente(provE);

        if (respuesta) {
            JOptionPane.showMessageDialog(null, "Se ha guardado satisfactoriamente un cliente en el sistema", "Guardado", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "El proveedor ya existe", "Guardado", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jLabelGuardarMouseClicked

    private void jLabelActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelActualizarMouseClicked
            
        boolean resp = false;
        
        /**
         *Se realizan las validaciones de los campos de texto*/
        
        if (txtRazon_Social.getText().trim().length() > 0) {
            provE.setRazon_social(txtRazon_Social.getText());
        } else {
            JOptionPane.showMessageDialog(null, "Por favor ingrese la Razón Social", "Datos Faltantes", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (txtDireccion.getText().trim().length() > 0) {
            provE.setDireccion(txtDireccion.getText());
        } else {
            JOptionPane.showMessageDialog(null, "Por favor ingrese la Dirección", "Datos Faltantes", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (txtTelefono.getText().trim().length() > 0) {
            provE.setTelefono(txtTelefono.getText());
        } else {
            JOptionPane.showMessageDialog(null, "Por favor ingrese el Teléfono", "Datos Faltantes", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (txtRepresentante_Legal.getText().trim().length() > 0) {
            provE.setRepresentante_legal(txtRepresentante_Legal.getText());
        } else {
            JOptionPane.showMessageDialog(null, "Por favor ingrese el Representante Legal", "Datos Faltantes", JOptionPane.ERROR_MESSAGE);
            return;
        }

        provE.setRegimen_tributario((String) cboRegimen_Tributario.getSelectedItem());


        boolean respuesta = provN.actualizarCliente(provE);


        if (respuesta == true) {
            JOptionPane.showMessageDialog(null, "Se ha actualizado satisfactoriamente", "Guardado", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Hubo un error en el proceso de actualización del Cliente", "Guardado", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jLabelActualizarMouseClicked

    private void jLabelConsultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelConsultarMouseClicked
        
        /**
         *Se realiza la validación de la cédula del cliente*/        
        String nit = JOptionPane.showInputDialog(this, "Por favor ingrese el NIT o Cédula del Cliente", "Consultar", JOptionPane.INFORMATION_MESSAGE); //Ventana para ingresar texto        
        provE = provN.consultarCliente(nit);
        
        /**
         * Se llenan los campos de texto con los respectivos datos*/
        
        if (provE != null) {
            txtNIT.setText(provE.getNIT());
            txtRazon_Social.setText(provE.getRazon_social());
            txtDireccion.setText(provE.getDireccion());
            txtTelefono.setText(provE.getTelefono());
            txtRepresentante_Legal.setText(provE.getRepresentante_legal());
            cboRegimen_Tributario.setSelectedItem((String) provE.getRegimen_tributario());

            txtNIT.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(this, "El cliente no se ha encontrado", "Consultar", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jLabelConsultarMouseClicked

    private void jLabelEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEliminarMouseClicked
        
        /**
         *Se realiza la validación de la cédula del cliente*/
        
        String nit = JOptionPane.showInputDialog(this, "Por favor ingrese el NIT del cliente a eliminar", "Eliminar", JOptionPane.INFORMATION_MESSAGE); //Ventana para ingresar texto
        
        /**
         *Se verifica la existencia del cliente*/
        
        if (provN.eliminarCliente(nit)) {
            JOptionPane.showMessageDialog(this, "El cliente ha sido eliminado", "Eliminar", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "El cliente no se ha encontrado", "Eliminar", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jLabelEliminarMouseClicked

    private void jLabelLimpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLimpiarMouseClicked
        txtNIT.setText("");
        txtRazon_Social.setText("");
        txtDireccion.setText("");
        txtTelefono.setText("");
        txtRepresentante_Legal.setText("");
        
        txtNIT.setEnabled(true);
    }//GEN-LAST:event_jLabelLimpiarMouseClicked

    private void jLabelImprimirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelImprimirMouseClicked
        provN.imprimirLista();
    }//GEN-LAST:event_jLabelImprimirMouseClicked

    private void jLabelInsumosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelInsumosMouseClicked
        FInsumosE fIns = new FInsumosE();
        this.setVisible(false);
        fIns.setVisible(true);
    }//GEN-LAST:event_jLabelInsumosMouseClicked

    private void jLabelClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelClientesMouseClicked
        FClientesE fCli = new FClientesE();
        this.setVisible(false);
        fCli.setVisible(true);
    }//GEN-LAST:event_jLabelClientesMouseClicked

    private void jLabelObrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelObrasMouseClicked
        FObrasE fObr = new FObrasE();
        this.setVisible(false);
        fObr.setVisible(true);
    }//GEN-LAST:event_jLabelObrasMouseClicked

    private void jLabelProveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelProveedoresMouseClicked
        FProveedoresE fProv = new FProveedoresE();
        this.setVisible(false);
        fProv.setVisible(true);
    }//GEN-LAST:event_jLabelProveedoresMouseClicked

    private void jLabelProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelProductosMouseClicked
        FProductosE fPro = new FProductosE();
        this.setVisible(false);
        fPro.setVisible(true);
    }//GEN-LAST:event_jLabelProductosMouseClicked

    private void jLabelCloseSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseSesionMouseClicked
        int confirmar = JOptionPane.showConfirmDialog(null, "¿Está seguro que desea cerrar la sesión?", "Salir", JOptionPane.YES_NO_OPTION);

        if (JOptionPane.YES_OPTION == confirmar) {
            try {
                InicioSesion is = new InicioSesion();
                this.dispose();
                is.setVisible(true);
            } catch (Exception ex) {
                Logger.getLogger(FClientesE.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jLabelCloseSesionMouseClicked

    private void jLabelConfiguracionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelConfiguracionMouseClicked
        try {
            ConfiguracionCuentaE cc = new ConfiguracionCuentaE();
            this.setVisible(false);
            cc.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(ConfiguracionCuentaE.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabelConfiguracionMouseClicked

    private void jLabelMenuPrincipal3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMenuPrincipal3MouseClicked
        MenuPrincipalE mpe = new MenuPrincipalE();
        this.setVisible(false);
        mpe.setVisible(true);
    }//GEN-LAST:event_jLabelMenuPrincipal3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FProveedores().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cboRegimen_Tributario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelActualizar;
    private javax.swing.JLabel jLabelClientes;
    private javax.swing.JLabel jLabelCloseSesion;
    private javax.swing.JLabel jLabelConfiguracion;
    private javax.swing.JLabel jLabelConsultar;
    private javax.swing.JLabel jLabelEliminar;
    private javax.swing.JLabel jLabelGuardar;
    private javax.swing.JLabel jLabelImprimir;
    private javax.swing.JLabel jLabelInsumos;
    private javax.swing.JLabel jLabelLimpiar;
    private javax.swing.JLabel jLabelMenuPrincipal3;
    private javax.swing.JLabel jLabelObras;
    private javax.swing.JLabel jLabelProductos;
    private javax.swing.JLabel jLabelProveedores;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNIT;
    private javax.swing.JTextField txtRazon_Social;
    private javax.swing.JTextField txtRepresentante_Legal;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
