/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mallas.interfaz;

import com.mallas.entidades.EntClientes;
import com.mallas.entidades.EntObras;
import com.mallas.negocio.ClienteNegocio;
import com.mallas.negocio.ObraNegocio;
import com.toedter.calendar.JDateChooser;
import java.awt.Color;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author samsung
 */
public class FObras extends javax.swing.JFrame {

    /**
     * Creates new form FObras
     */
    ObraNegocio obraN = new ObraNegocio();
    EntObras obraE = new EntObras();
    EntClientes cliE = new EntClientes();
    ClienteNegocio cliN = new ClienteNegocio();
    String a = "Medellín", b = "Barbosa", c = "Bello", d = "Caldas", e = "Copacabana", f = "Envigado",
            g = "Girardota", h = "Itaguí", i = "La Estrella", j = "Sabaneta", k = "Rio Claro", l = "Ocaña", m = "Buga";

    public FObras() {
        initComponents();
        super.setLocationRelativeTo(null);
        cboCiudad.addItem(a);
        cboCiudad.addItem(b);
        cboCiudad.addItem(c);
        cboCiudad.addItem(d);
        cboCiudad.addItem(e);
        cboCiudad.addItem(f);
        cboCiudad.addItem(g);
        cboCiudad.addItem(h);
        cboCiudad.addItem(i);
        cboCiudad.addItem(j);
        cboCiudad.addItem(k);
        cboCiudad.addItem(l);
        cboCiudad.addItem(m);
        setIconImage(new ImageIcon(getClass().getResource("/com/mallas/imagenes/Desktop Icon.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtReferencia = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        cboCiudad = new javax.swing.JComboBox();
        txtDireccion = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cboEstado = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabelGuardar = new javax.swing.JLabel();
        jLabelEditar = new javax.swing.JLabel();
        jLabelConsultar = new javax.swing.JLabel();
        jLabelEliminar = new javax.swing.JLabel();
        jLabelLimpiar = new javax.swing.JLabel();
        jLabelImprimir = new javax.swing.JLabel();
        calendarFI = new com.toedter.calendar.JDateChooser();
        calendarFF = new com.toedter.calendar.JDateChooser();
        txtCliente = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabelInsumos3 = new javax.swing.JLabel();
        jLabelClientes3 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabelEmpleados3 = new javax.swing.JLabel();
        jLabelUsuarios3 = new javax.swing.JLabel();
        jLabelObras3 = new javax.swing.JLabel();
        jLabelProveedores3 = new javax.swing.JLabel();
        jLabelProductos3 = new javax.swing.JLabel();
        jLabelCloseSesion3 = new javax.swing.JLabel();
        jLabelSettings = new javax.swing.JLabel();
        jLabelMenuPrincipal3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(40, 40, 40)));
        jPanel1.setPreferredSize(new java.awt.Dimension(736, 482));

        cboCiudad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Medellín", "Barbosa", "Bello", "Caldas", "Copacabana", "Envigado", "Girardota", "Guarne", "Itagui", "La Estrella", "Sabaneta", "Rio Claro", "Ocaña", "Buga" }));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("* Estado:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("* Direccion:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("* Ciudad:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("  Fecha Final:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("* Fecha Inicio:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("* Nombre:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("* Cliente:");

        cboEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Activa", "Inactiva" }));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("* Referencia:");

        jPanel4.setBackground(new java.awt.Color(40, 40, 40));
        jPanel4.setPreferredSize(new java.awt.Dimension(192, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Administración de Obras");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelGuardar.setBackground(new java.awt.Color(8, 102, 198));
        jLabelGuardar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelGuardar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGuardar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelGuardar.setText("Guardar");
        jLabelGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelGuardar.setOpaque(true);
        jLabelGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelGuardarMouseClicked(evt);
            }
        });

        jLabelEditar.setBackground(new java.awt.Color(8, 102, 198));
        jLabelEditar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelEditar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEditar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEditar.setText("Actualizar");
        jLabelEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelEditar.setOpaque(true);
        jLabelEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelEditarMouseClicked(evt);
            }
        });

        jLabelConsultar.setBackground(new java.awt.Color(8, 102, 198));
        jLabelConsultar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelConsultar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelConsultar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelConsultar.setText("Consultar");
        jLabelConsultar.setToolTipText("");
        jLabelConsultar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelConsultar.setOpaque(true);
        jLabelConsultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelConsultarMouseClicked(evt);
            }
        });

        jLabelEliminar.setBackground(new java.awt.Color(8, 102, 198));
        jLabelEliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelEliminar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEliminar.setText("Eliminar");
        jLabelEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelEliminar.setOpaque(true);
        jLabelEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelEliminarMouseClicked(evt);
            }
        });

        jLabelLimpiar.setBackground(new java.awt.Color(8, 102, 198));
        jLabelLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLimpiar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLimpiar.setText("Limpiar");
        jLabelLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelLimpiar.setOpaque(true);
        jLabelLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLimpiarMouseClicked(evt);
            }
        });

        jLabelImprimir.setBackground(new java.awt.Color(8, 102, 198));
        jLabelImprimir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelImprimir.setForeground(new java.awt.Color(255, 255, 255));
        jLabelImprimir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelImprimir.setText("Imprimir");
        jLabelImprimir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelImprimir.setOpaque(true);
        jLabelImprimir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelImprimirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtReferencia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(30, 30, 30)
                        .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cboCiudad, 0, 103, Short.MAX_VALUE)
                            .addComponent(calendarFI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(calendarFF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(141, Short.MAX_VALUE)
                .addComponent(jLabelGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(calendarFI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(calendarFF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(cboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(8, 102, 198));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mallas/imagenes/logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(40, 40, 40));

        jLabelInsumos3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelInsumos3.setForeground(new java.awt.Color(204, 204, 204));
        jLabelInsumos3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelInsumos3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mallas/imagenes/InsumosIcon.png"))); // NOI18N
        jLabelInsumos3.setText("Insumos");
        jLabelInsumos3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jLabelInsumos3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelInsumos3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelInsumos3MouseClicked(evt);
            }
        });

        jLabelClientes3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelClientes3.setForeground(new java.awt.Color(204, 204, 204));
        jLabelClientes3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelClientes3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mallas/imagenes/ClientesIcon.png"))); // NOI18N
        jLabelClientes3.setText("Clientes");
        jLabelClientes3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jLabelClientes3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClientes3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelClientes3MouseClicked(evt);
            }
        });

        jLabel17.setBackground(new java.awt.Color(35, 35, 35));
        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Navegación");
        jLabel17.setOpaque(true);

        jLabelEmpleados3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelEmpleados3.setForeground(new java.awt.Color(204, 204, 204));
        jLabelEmpleados3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEmpleados3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mallas/imagenes/PersonalIcon.png"))); // NOI18N
        jLabelEmpleados3.setText("Empleados");
        jLabelEmpleados3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jLabelEmpleados3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelEmpleados3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelEmpleados3MouseClicked(evt);
            }
        });

        jLabelUsuarios3.setBackground(new java.awt.Color(51, 51, 51));
        jLabelUsuarios3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelUsuarios3.setForeground(new java.awt.Color(204, 204, 204));
        jLabelUsuarios3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelUsuarios3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mallas/imagenes/PersonalIcon.png"))); // NOI18N
        jLabelUsuarios3.setText("Usuarios");
        jLabelUsuarios3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jLabelUsuarios3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelUsuarios3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelUsuarios3MouseClicked(evt);
            }
        });

        jLabelObras3.setBackground(new java.awt.Color(51, 51, 51));
        jLabelObras3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelObras3.setForeground(new java.awt.Color(204, 204, 204));
        jLabelObras3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelObras3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mallas/imagenes/ObrasIcon.png"))); // NOI18N
        jLabelObras3.setText("Obras");
        jLabelObras3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jLabelObras3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelObras3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelObras3MouseClicked(evt);
            }
        });

        jLabelProveedores3.setBackground(new java.awt.Color(51, 51, 51));
        jLabelProveedores3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelProveedores3.setForeground(new java.awt.Color(204, 204, 204));
        jLabelProveedores3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProveedores3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mallas/imagenes/ProveedoresIcon.png"))); // NOI18N
        jLabelProveedores3.setText("Proveedores");
        jLabelProveedores3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jLabelProveedores3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelProveedores3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelProveedores3MouseClicked(evt);
            }
        });

        jLabelProductos3.setBackground(new java.awt.Color(51, 51, 51));
        jLabelProductos3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelProductos3.setForeground(new java.awt.Color(204, 204, 204));
        jLabelProductos3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProductos3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mallas/imagenes/ProductosIcon.png"))); // NOI18N
        jLabelProductos3.setText("Productos");
        jLabelProductos3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jLabelProductos3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelProductos3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelProductos3MouseClicked(evt);
            }
        });

        jLabelCloseSesion3.setBackground(new java.awt.Color(51, 51, 51));
        jLabelCloseSesion3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelCloseSesion3.setForeground(new java.awt.Color(204, 204, 204));
        jLabelCloseSesion3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCloseSesion3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mallas/imagenes/CerrarSesion.png"))); // NOI18N
        jLabelCloseSesion3.setText("Cerrar Sesión");
        jLabelCloseSesion3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jLabelCloseSesion3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelCloseSesion3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseSesion3MouseClicked(evt);
            }
        });

        jLabelSettings.setBackground(new java.awt.Color(51, 51, 51));
        jLabelSettings.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelSettings.setForeground(new java.awt.Color(204, 204, 204));
        jLabelSettings.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mallas/imagenes/SettingsIcon.png"))); // NOI18N
        jLabelSettings.setText("Configuración de cuenta");
        jLabelSettings.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jLabelSettings.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelSettings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSettingsMouseClicked(evt);
            }
        });

        jLabelMenuPrincipal3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelMenuPrincipal3.setForeground(new java.awt.Color(204, 204, 204));
        jLabelMenuPrincipal3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMenuPrincipal3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mallas/imagenes/Home.png"))); // NOI18N
        jLabelMenuPrincipal3.setText("Menú Principal");
        jLabelMenuPrincipal3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jLabelMenuPrincipal3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMenuPrincipal3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabelMenuPrincipal3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMenuPrincipal3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelInsumos3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelClientes3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelEmpleados3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelUsuarios3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelObras3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelProveedores3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelProductos3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelSettings, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
            .addComponent(jLabelCloseSesion3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelMenuPrincipal3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(jLabelMenuPrincipal3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelInsumos3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelClientes3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelEmpleados3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelUsuarios3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelObras3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelProveedores3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelProductos3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCloseSesion3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelGuardarMouseClicked
        EntObras cabeza = null;
        obraE.setNext(cabeza);

        /**
         *Se realizan las validaciones de los campos de texto*/
        
        if (txtReferencia.getText().trim().length() > 0) {
            obraE.setReferencia(txtReferencia.getText());
        } else {
            JOptionPane.showMessageDialog(null, "Por favor ingrese la Referencia de la obra", "Datos Faltantes", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (txtNombre.getText().trim().length() > 0) {
            obraE.setNombre(txtNombre.getText());
        } else {
            JOptionPane.showMessageDialog(null, "Por favor ingrese el Nombre de la obra", "Datos Faltantes", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (txtCliente.getText().trim().length() > 0) {
            obraE.setNombre_cliente(txtCliente.getText());
        } else {
            JOptionPane.showMessageDialog(null, "Por favor ingrese el Nombre de la obra", "Datos Faltantes", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (calendarFI.getDateFormatString().trim().length() > 0) { //trim= quitar espacios en blanco, length= contar los espacios.
            int año = calendarFI.getCalendar().get(java.util.Calendar.YEAR);
            int mes = calendarFI.getCalendar().get(java.util.Calendar.MONTH) + 1;
            int dia = calendarFI.getCalendar().get(java.util.Calendar.DATE);
            String fechaI = dia + "/" + mes + "/" + año;
            obraE.setFecha_inicio(fechaI); //sacar informacion del cuadro de texto para meterlo en insumo. 

        } else {
            JOptionPane.showMessageDialog(null, "Por favor ingrese la Fecha de Inicio", "Datos Faltantes", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (calendarFF.getDateFormatString().trim().length() > 0) {
            int año = calendarFF.getCalendar().get(java.util.Calendar.YEAR);
            int mes = calendarFF.getCalendar().get(java.util.Calendar.MONTH) + 1;
            int dia = calendarFF.getCalendar().get(java.util.Calendar.DATE);
            String fechaF = dia + "/" + mes + "/" + año;
            obraE.setFecha_final(fechaF); //sacar informacion del cuadro de texto para meterlo en insumo. 

        }               

        obraE.setCiudad(cboCiudad.getSelectedItem().toString());

        if (txtDireccion.getText().trim().length() > 0) {
            obraE.setDireccion(txtDireccion.getText());
        } else {
            JOptionPane.showMessageDialog(null, "Por favor ingrese la Dirección de la obra", "Datos Faltantes", JOptionPane.ERROR_MESSAGE);
            return;
        }

        obraE.setEstado(cboEstado.getSelectedItem().toString());

        boolean respuesta = obraN.guardarObraEnt(obraE);

        if (respuesta) {
            JOptionPane.showMessageDialog(null, "Se ha guardado satisfactoriamente una obra en el sistema", "Guardado", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "La obra ya existe", "Guardado", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jLabelGuardarMouseClicked

    private void jLabelEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEditarMouseClicked
        
        /**
         *Se realizan las validaciones de los campos de texto*/
        
        if (txtNombre.getText().trim().length() > 0) {
            obraE.setNombre(txtNombre.getText());
        } else {
            JOptionPane.showMessageDialog(null, "Por favor ingrese el Nombre de la obra", "Datos Faltantes", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (txtCliente.getText().trim().length() > 0) {
            obraE.setNombre_cliente(txtCliente.getText());
        } else {
            JOptionPane.showMessageDialog(null, "Por favor ingrese el Nombre de la obra", "Datos Faltantes", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (calendarFI.getDateFormatString().trim().length() > 0) { //trim= quitar espacios en blanco, length= contar los espacios.
            int año = calendarFI.getCalendar().get(java.util.Calendar.YEAR);
            int mes = calendarFI.getCalendar().get(java.util.Calendar.MONTH) + 1;
            int dia = calendarFI.getCalendar().get(java.util.Calendar.DATE);
            String fecha = dia + "/" + mes + "/" + año;
            obraE.setFecha_inicio(fecha); //sacar informacion del cuadro de texto para meterlo en insumo. 

        } else {
            JOptionPane.showMessageDialog(null, "Por favor ingrese la Fecha de Inicio", "Datos Faltantes", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (calendarFF.getDateFormatString().trim().length() > 0) {
            int año = calendarFF.getCalendar().get(java.util.Calendar.YEAR);
            int mes = calendarFF.getCalendar().get(java.util.Calendar.MONTH) + 1;
            int dia = calendarFF.getCalendar().get(java.util.Calendar.DATE);
            String fecha = dia + "/" + mes + "/" + año;
            obraE.setFecha_final(fecha); //sacar informacion del cuadro de texto para meterlo en insumo. 

        }

        obraE.setCiudad(cboCiudad.getSelectedItem().toString());

        if (txtDireccion.getText().trim().length() > 0) {
            obraE.setDireccion(txtDireccion.getText());
        } else {
            JOptionPane.showMessageDialog(null, "Por favor ingrese la Dirección de la obra", "Datos Faltantes", JOptionPane.ERROR_MESSAGE);
            return;
        }

        obraE.setEstado(cboEstado.getSelectedItem().toString());

        boolean respuesta = obraN.actualizarObraEnt(obraE);

        if (respuesta) {
            JOptionPane.showMessageDialog(null, "Se ha actualizado satisfactoriamente", "Actualizar", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Hubo un error en el proceso de actualización de la obra", "Actualizar", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jLabelEditarMouseClicked

    private void jLabelConsultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelConsultarMouseClicked
        
        /**
         *Se realiza la validación de la referencia de la obra*/
         
        String referencia = JOptionPane.showInputDialog(this, "Por favor ingrese la Referencia de la obra", "Consultar", JOptionPane.INFORMATION_MESSAGE); //Ventana para ingresar texto        
        obraE = obraN.consultarObraEnt(referencia);

        /**
         * Se llenan los campos de texto con los respectivos datos*/
        
        if (obraE != null) {
            txtReferencia.setText(obraE.getReferencia());
            txtNombre.setText(obraE.getNombre());
            txtCliente.setText(obraE.getNombre_cliente());
            calendarFI.setDateFormatString(obraE.getFecha_inicio());
            calendarFF.setDateFormatString(obraE.getFecha_final());
            cboCiudad.setSelectedItem(obraE.getCiudad());
            txtDireccion.setText(obraE.getDireccion());
            cboEstado.setSelectedItem(obraE.getEstado());

            txtReferencia.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(this, "La obra no se ha encontrado", "Consultar", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jLabelConsultarMouseClicked

    private void jLabelEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEliminarMouseClicked
       
        /**
         *Se realiza la validación de la referencia de la obra*/
        
        String referencia = JOptionPane.showInputDialog(this, "Por favor ingrese la Referencia de la obra a eliminar", "Eliminar", JOptionPane.INFORMATION_MESSAGE); //Ventana para ingresar texto

        /**
         *Se verifica la existencia de la obra*/  
        
        if (obraN.eliminarObraEnt(referencia)) {
            JOptionPane.showMessageDialog(this, "La obra ha sido eliminada", "Eliminar", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "La obra no se ha encontrado", "Eliminar", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jLabelEliminarMouseClicked

    private void jLabelLimpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLimpiarMouseClicked
        txtReferencia.setText("");
        txtNombre.setText("");
        calendarFI.setDateFormatString("");
        calendarFF.setDateFormatString("");
        txtDireccion.setText("");
        txtCliente.setText("");
        txtReferencia.setEnabled(true);
    }//GEN-LAST:event_jLabelLimpiarMouseClicked

    private void jLabelImprimirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelImprimirMouseClicked
        obraN.imprimirLista();
    }//GEN-LAST:event_jLabelImprimirMouseClicked

    private void jLabelInsumos3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelInsumos3MouseClicked
        FInsumos fIns = new FInsumos();
        this.setVisible(false);
        fIns.setVisible(true);
    }//GEN-LAST:event_jLabelInsumos3MouseClicked

    private void jLabelClientes3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelClientes3MouseClicked
        FClientes fCli = new FClientes();
        this.setVisible(false);
        fCli.setVisible(true);
    }//GEN-LAST:event_jLabelClientes3MouseClicked

    private void jLabelEmpleados3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEmpleados3MouseClicked
        FEmpleados fEmpl = new FEmpleados();
        this.setVisible(false);
        fEmpl.setVisible(true);
    }//GEN-LAST:event_jLabelEmpleados3MouseClicked

    private void jLabelUsuarios3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelUsuarios3MouseClicked
        try {
            FUsuarios fUsu = new FUsuarios();
            this.setVisible(false);
            fUsu.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(FUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabelUsuarios3MouseClicked

    private void jLabelObras3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelObras3MouseClicked
        FObras fObr = new FObras();
        this.setVisible(false);
        fObr.setVisible(true);
    }//GEN-LAST:event_jLabelObras3MouseClicked

    private void jLabelProveedores3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelProveedores3MouseClicked
        FProveedores fProv = new FProveedores();
        this.setVisible(false);
        fProv.setVisible(true);
    }//GEN-LAST:event_jLabelProveedores3MouseClicked

    private void jLabelProductos3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelProductos3MouseClicked
        FProductos fPro = new FProductos();
        this.setVisible(false);
        fPro.setVisible(true);
    }//GEN-LAST:event_jLabelProductos3MouseClicked

    private void jLabelCloseSesion3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseSesion3MouseClicked
        int confirmar = JOptionPane.showConfirmDialog(null, "¿Está seguro que desea cerrar la sesión?", "Salir", JOptionPane.YES_NO_OPTION);

        if (JOptionPane.YES_OPTION == confirmar) {
            try {
                InicioSesion is = new InicioSesion();
                this.dispose();
                is.setVisible(true);
            } catch (Exception ex) {
                Logger.getLogger(FUsuarios.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jLabelCloseSesion3MouseClicked

    private void jLabelSettingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSettingsMouseClicked
        try {
            ConfiguracionCuenta cc = new ConfiguracionCuenta();
            this.setVisible(false);
            cc.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(ConfiguracionCuenta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabelSettingsMouseClicked

    private void jLabelMenuPrincipal3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMenuPrincipal3MouseClicked
        MenuPrincipal mpe = new MenuPrincipal();
        this.setVisible(false);
        mpe.setVisible(true);
    }//GEN-LAST:event_jLabelMenuPrincipal3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FObras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FObras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FObras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FObras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FObras().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser calendarFF;
    private com.toedter.calendar.JDateChooser calendarFI;
    private javax.swing.JComboBox cboCiudad;
    private javax.swing.JComboBox cboEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelClientes3;
    private javax.swing.JLabel jLabelCloseSesion3;
    private javax.swing.JLabel jLabelConsultar;
    private javax.swing.JLabel jLabelEditar;
    private javax.swing.JLabel jLabelEliminar;
    private javax.swing.JLabel jLabelEmpleados3;
    private javax.swing.JLabel jLabelGuardar;
    private javax.swing.JLabel jLabelImprimir;
    private javax.swing.JLabel jLabelInsumos3;
    private javax.swing.JLabel jLabelLimpiar;
    private javax.swing.JLabel jLabelMenuPrincipal3;
    private javax.swing.JLabel jLabelObras3;
    private javax.swing.JLabel jLabelProductos3;
    private javax.swing.JLabel jLabelProveedores3;
    private javax.swing.JLabel jLabelSettings;
    private javax.swing.JLabel jLabelUsuarios3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtReferencia;
    // End of variables declaration//GEN-END:variables
}
