/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mallas.interfaz;

import com.mallas.entidades.EntProductos;
import com.mallas.negocio.ProductoNegocio;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author samsung
 */
public class FProductos extends javax.swing.JFrame {

    /**
     * Creates new form FProductos
     */
    public FProductos() {
        initComponents();
        super.setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/com/mallas/imagenes/Desktop Icon.png")).getImage());
    }
    EntProductos prodE = new EntProductos();
    ProductoNegocio prodN = new ProductoNegocio();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        txtCodigo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        spCantidad = new javax.swing.JSpinner();
        txtStock = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabelGuardar = new javax.swing.JLabel();
        jLabelEditar = new javax.swing.JLabel();
        jLabelConsultar = new javax.swing.JLabel();
        jLabelEliminar = new javax.swing.JLabel();
        jLabelLimpiar = new javax.swing.JLabel();
        jLabelImprimir = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabelInsumos = new javax.swing.JLabel();
        jLabelClientes = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabelEmpleados = new javax.swing.JLabel();
        jLabelUsuarios = new javax.swing.JLabel();
        jLabelObras = new javax.swing.JLabel();
        jLabelProveedores = new javax.swing.JLabel();
        jLabelProductos = new javax.swing.JLabel();
        jLabelCloseSesion = new javax.swing.JLabel();
        jLabelConfiguracion = new javax.swing.JLabel();
        jLabelMenuPrincipal3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(40, 40, 40)));
        jPanel1.setPreferredSize(new java.awt.Dimension(736, 482));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("* Código:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("* Nombre:");

        txtDescripcion.setColumns(20);
        txtDescripcion.setLineWrap(true);
        txtDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtDescripcion);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("* Cantidad:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Descripción:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("* Precio:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("* Stock:");

        jPanel2.setBackground(new java.awt.Color(40, 40, 40));
        jPanel2.setPreferredSize(new java.awt.Dimension(500, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Administración de Productos");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap())
        );

        jLabelGuardar.setBackground(new java.awt.Color(8, 102, 198));
        jLabelGuardar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelGuardar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGuardar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelGuardar.setText("Guardar");
        jLabelGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelGuardar.setOpaque(true);
        jLabelGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelGuardarMouseClicked(evt);
            }
        });

        jLabelEditar.setBackground(new java.awt.Color(8, 102, 198));
        jLabelEditar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelEditar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEditar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEditar.setText("Actualizar");
        jLabelEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelEditar.setOpaque(true);
        jLabelEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelEditarMouseClicked(evt);
            }
        });

        jLabelConsultar.setBackground(new java.awt.Color(8, 102, 198));
        jLabelConsultar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelConsultar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelConsultar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelConsultar.setText("Consultar");
        jLabelConsultar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelConsultar.setOpaque(true);
        jLabelConsultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelConsultarMouseClicked(evt);
            }
        });

        jLabelEliminar.setBackground(new java.awt.Color(8, 102, 198));
        jLabelEliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelEliminar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEliminar.setText("Eliminar");
        jLabelEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelEliminar.setOpaque(true);
        jLabelEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelEliminarMouseClicked(evt);
            }
        });

        jLabelLimpiar.setBackground(new java.awt.Color(8, 102, 198));
        jLabelLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLimpiar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLimpiar.setText("Limpiar");
        jLabelLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelLimpiar.setOpaque(true);
        jLabelLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLimpiarMouseClicked(evt);
            }
        });

        jLabelImprimir.setBackground(new java.awt.Color(8, 102, 198));
        jLabelImprimir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelImprimir.setForeground(new java.awt.Color(255, 255, 255));
        jLabelImprimir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelImprimir.setText("Imprimir");
        jLabelImprimir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelImprimir.setOpaque(true);
        jLabelImprimir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelImprimirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPrecio)
                    .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                    .addComponent(txtCodigo))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(spCantidad, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtStock, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(133, 133, 133))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(jLabelGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(spCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(40, 40, 40));
        jPanel5.setPreferredSize(new java.awt.Dimension(272, 493));

        jLabelInsumos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelInsumos.setForeground(new java.awt.Color(204, 204, 204));
        jLabelInsumos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelInsumos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mallas/imagenes/InsumosIcon.png"))); // NOI18N
        jLabelInsumos.setText("Insumos");
        jLabelInsumos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jLabelInsumos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelInsumos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelInsumosMouseClicked(evt);
            }
        });

        jLabelClientes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelClientes.setForeground(new java.awt.Color(204, 204, 204));
        jLabelClientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mallas/imagenes/ClientesIcon.png"))); // NOI18N
        jLabelClientes.setText("Clientes");
        jLabelClientes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jLabelClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelClientesMouseClicked(evt);
            }
        });

        jLabel14.setBackground(new java.awt.Color(35, 35, 35));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Navegación");
        jLabel14.setOpaque(true);

        jLabelEmpleados.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelEmpleados.setForeground(new java.awt.Color(204, 204, 204));
        jLabelEmpleados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mallas/imagenes/PersonalIcon.png"))); // NOI18N
        jLabelEmpleados.setText("Empleados");
        jLabelEmpleados.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jLabelEmpleados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelEmpleadosMouseClicked(evt);
            }
        });

        jLabelUsuarios.setBackground(new java.awt.Color(51, 51, 51));
        jLabelUsuarios.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelUsuarios.setForeground(new java.awt.Color(204, 204, 204));
        jLabelUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mallas/imagenes/PersonalIcon.png"))); // NOI18N
        jLabelUsuarios.setText("Usuarios");
        jLabelUsuarios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jLabelUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelUsuariosMouseClicked(evt);
            }
        });

        jLabelObras.setBackground(new java.awt.Color(51, 51, 51));
        jLabelObras.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelObras.setForeground(new java.awt.Color(204, 204, 204));
        jLabelObras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelObras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mallas/imagenes/ObrasIcon.png"))); // NOI18N
        jLabelObras.setText("Obras");
        jLabelObras.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jLabelObras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelObras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelObrasMouseClicked(evt);
            }
        });

        jLabelProveedores.setBackground(new java.awt.Color(51, 51, 51));
        jLabelProveedores.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelProveedores.setForeground(new java.awt.Color(204, 204, 204));
        jLabelProveedores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mallas/imagenes/ProveedoresIcon.png"))); // NOI18N
        jLabelProveedores.setText("Proveedores");
        jLabelProveedores.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jLabelProveedores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelProveedoresMouseClicked(evt);
            }
        });

        jLabelProductos.setBackground(new java.awt.Color(51, 51, 51));
        jLabelProductos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelProductos.setForeground(new java.awt.Color(204, 204, 204));
        jLabelProductos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mallas/imagenes/ProductosIcon.png"))); // NOI18N
        jLabelProductos.setText("Productos");
        jLabelProductos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jLabelProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelProductosMouseClicked(evt);
            }
        });

        jLabelCloseSesion.setBackground(new java.awt.Color(51, 51, 51));
        jLabelCloseSesion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelCloseSesion.setForeground(new java.awt.Color(204, 204, 204));
        jLabelCloseSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCloseSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mallas/imagenes/CerrarSesion.png"))); // NOI18N
        jLabelCloseSesion.setText("Cerrar Sesión");
        jLabelCloseSesion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jLabelCloseSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelCloseSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseSesionMouseClicked(evt);
            }
        });

        jLabelConfiguracion.setBackground(new java.awt.Color(51, 51, 51));
        jLabelConfiguracion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelConfiguracion.setForeground(new java.awt.Color(204, 204, 204));
        jLabelConfiguracion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelConfiguracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mallas/imagenes/SettingsIcon.png"))); // NOI18N
        jLabelConfiguracion.setText("Configuración de cuenta");
        jLabelConfiguracion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jLabelConfiguracion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelConfiguracion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelConfiguracionMouseClicked(evt);
            }
        });

        jLabelMenuPrincipal3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelMenuPrincipal3.setForeground(new java.awt.Color(204, 204, 204));
        jLabelMenuPrincipal3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMenuPrincipal3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mallas/imagenes/Home.png"))); // NOI18N
        jLabelMenuPrincipal3.setText("Menú Principal");
        jLabelMenuPrincipal3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jLabelMenuPrincipal3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMenuPrincipal3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabelMenuPrincipal3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMenuPrincipal3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelInsumos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelClientes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelEmpleados, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelObras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelProveedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelCloseSesion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelConfiguracion, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
            .addComponent(jLabelMenuPrincipal3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(jLabelMenuPrincipal3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelInsumos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelObras, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelConfiguracion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCloseSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(8, 102, 198));
        jPanel3.setPreferredSize(new java.awt.Dimension(1024, 106));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mallas/imagenes/logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelInsumosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelInsumosMouseClicked
        FInsumos fIns = new FInsumos();
        this.setVisible(false);
        fIns.setVisible(true);
    }//GEN-LAST:event_jLabelInsumosMouseClicked

    private void jLabelClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelClientesMouseClicked
        FClientes fCli = new FClientes();
        this.setVisible(false);
        fCli.setVisible(true);
    }//GEN-LAST:event_jLabelClientesMouseClicked

    private void jLabelEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEmpleadosMouseClicked
        FEmpleados fEmpl = new FEmpleados();
        this.setVisible(false);
        fEmpl.setVisible(true);
    }//GEN-LAST:event_jLabelEmpleadosMouseClicked

    private void jLabelUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelUsuariosMouseClicked
        try {
            FUsuarios fUsu = new FUsuarios();
            this.setVisible(false);
            fUsu.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(FProductos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabelUsuariosMouseClicked

    private void jLabelObrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelObrasMouseClicked
        FObras fObr = new FObras();
        this.setVisible(false);
        fObr.setVisible(true);
    }//GEN-LAST:event_jLabelObrasMouseClicked

    private void jLabelProveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelProveedoresMouseClicked
        FProveedores fProv = new FProveedores();
        this.setVisible(false);
        fProv.setVisible(true);
    }//GEN-LAST:event_jLabelProveedoresMouseClicked

    private void jLabelProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelProductosMouseClicked
        FProductos fPro = new FProductos();
        this.setVisible(false);
        fPro.setVisible(true);
    }//GEN-LAST:event_jLabelProductosMouseClicked

    private void jLabelGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelGuardarMouseClicked
        EntProductos cabeza = null;
        prodE.setNext(cabeza);

        if (txtCodigo.getText().trim().length() > 0) {
            prodE.setCodigo_producto(txtCodigo.getText());
        } else {
            JOptionPane.showMessageDialog(null, "Por favor ingrese el Código del Producto", "Datos Faltantes", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (txtNombre.getText().trim().length() > 0) {
            prodE.setNombre(txtNombre.getText());
        } else {
            JOptionPane.showMessageDialog(null, "Por favor ingrese el Nombre del Producto", "Datos Faltantes", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int precio = Integer.parseInt(txtPrecio.getText());

        if (txtPrecio.getText().trim().length() > 0) {
            prodE.setPrecio(precio);
        } else {
            JOptionPane.showMessageDialog(null, "Por favor ingrese el Precio del Producto", "Datos Faltantes", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int stock = Integer.parseInt(txtStock.getText());

        if (txtStock.getText().trim().length() > 0) {
            prodE.setStock(stock);
        } else {
            JOptionPane.showMessageDialog(null, "Por favor ingrese la Cantidad en Stock del Producto", "Datos Faltantes", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (txtDescripcion.getText().trim().length() > 0) {
            prodE.setDescripcion(txtDescripcion.getText());
        } else {
            prodE.setDescripcion("Sin Descripción");
        }

        int cantidad = (int) spCantidad.getValue();

        if (cantidad > 0) {
            prodE.setCantidad(cantidad);
        } else {
            if (cantidad <= 0) {
                JOptionPane.showMessageDialog(null, "La Cantidad a almacenar del Producto debe ser mayor a 0 (cero)", "Datos Faltantes", JOptionPane.ERROR_MESSAGE);
                return;
            }
            JOptionPane.showMessageDialog(null, "Por favor ingrese la Cantidad a almacenar del Producto", "Datos Faltantes", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        boolean respuesta = prodN.guardarProducto(prodE);
        
        if(respuesta){
            JOptionPane.showMessageDialog(null, "Se ha guardado satisfactoriamente un producto en el sistema", "Guardado", JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(null, "El producto ya existe", "Guardado", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jLabelGuardarMouseClicked

    private void jLabelEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEditarMouseClicked
        if (txtNombre.getText().trim().length() > 0) {
            prodE.setNombre(txtNombre.getText());
        } else {
            JOptionPane.showMessageDialog(null, "Por favor ingrese el Nombre del Producto", "Datos Faltantes", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int precio = Integer.parseInt(txtPrecio.getText());

        if (txtPrecio.getText().trim().length() > 0) {
            prodE.setPrecio(precio);
        } else {
            JOptionPane.showMessageDialog(null, "Por favor ingrese el Precio del Producto", "Datos Faltantes", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int stock = Integer.parseInt(txtStock.getText());

        if (txtStock.getText().trim().length() > 0) {
            prodE.setStock(stock);
        } else {
            JOptionPane.showMessageDialog(null, "Por favor ingrese la Cantidad en Stock del Producto", "Datos Faltantes", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (txtDescripcion.getText().trim().length() > 0) {
            prodE.setDescripcion(txtDescripcion.getText());
        } else {
            prodE.setDescripcion("Sin Descripción");
        }

        int cantidad = (int) spCantidad.getValue();

        if (cantidad > 0) {
            prodE.setCantidad(cantidad);
        } else {
            if (cantidad <= 0) {
                JOptionPane.showMessageDialog(null, "La Cantidad a almacenar del Producto debe ser mayor a 0 (cero)", "Datos Faltantes", JOptionPane.ERROR_MESSAGE);
                return;
            }
            JOptionPane.showMessageDialog(null, "Por favor ingrese la Cantidad a almacenar del Producto", "Datos Faltantes", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        boolean respuesta = prodN.actualizarProducto(prodE);
        
        if(respuesta){
            JOptionPane.showMessageDialog(null, "Se ha actualizado satisfactoriamente", "Actualizar", JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(null, "Hubo un error en el proceso de actualización del producto", "Actualizar", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jLabelEditarMouseClicked

    private void jLabelConsultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelConsultarMouseClicked
        String codigo = JOptionPane.showInputDialog(this, "Por favor ingrese el código del producto", "Consultar", JOptionPane.INFORMATION_MESSAGE);
        prodE = prodN.consutlarProducto(codigo);
        
        if(prodE != null){
            txtCodigo.setText(prodE.getCodigo_producto());
            txtNombre.setText(prodE.getNombre());
            txtPrecio.setText(Integer.toString(prodE.getPrecio()));
            txtStock.setText(Integer.toString(prodE.getStock()));
            txtDescripcion.setText(prodE.getDescripcion());
            spCantidad.setValue(prodE.getCantidad()); 
            
            txtCodigo.setEnabled(false);
        }else{
            JOptionPane.showMessageDialog(this, "El producto no se ha encontrado", "Consultar", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jLabelConsultarMouseClicked

    private void jLabelEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEliminarMouseClicked
        String codigo = JOptionPane.showInputDialog(this, "Por favor ingrese el código del producto a eliminar", "Eliminar", JOptionPane.INFORMATION_MESSAGE); //Ventana para ingresar texto
        
        if(prodN.eliminarProducto(codigo)){
            JOptionPane.showMessageDialog(this, "El producto ha sido eliminado", "Eliminar", JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(this, "El producto no se ha encontrado", "Eliminar", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jLabelEliminarMouseClicked

    private void jLabelLimpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLimpiarMouseClicked
         
        txtCodigo.setText("");
        txtNombre.setText("");
        txtPrecio.setText("");
        txtStock.setText("");
        txtDescripcion.setText("");
        spCantidad.setToolTipText("");
        
        txtCodigo.setEnabled(true);
    }//GEN-LAST:event_jLabelLimpiarMouseClicked

    private void jLabelImprimirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelImprimirMouseClicked
        prodN.imprimirLista();
    }//GEN-LAST:event_jLabelImprimirMouseClicked

    private void jLabelCloseSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseSesionMouseClicked
        int confirmar = JOptionPane.showConfirmDialog(null, "¿Está seguro que desea cerrar la sesión?", "Salir", JOptionPane.YES_NO_OPTION);

        if (JOptionPane.YES_OPTION == confirmar) {
            try {
                InicioSesion is = new InicioSesion();
                this.dispose();
                is.setVisible(true);
            } catch (Exception ex) {
                Logger.getLogger(FProductos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jLabelCloseSesionMouseClicked

    private void jLabelConfiguracionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelConfiguracionMouseClicked
        try {
            ConfiguracionCuenta cc = new ConfiguracionCuenta();
            this.setVisible(false);
            cc.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(ConfiguracionCuenta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabelConfiguracionMouseClicked

    private void jLabelMenuPrincipal3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMenuPrincipal3MouseClicked
        MenuPrincipal mpe = new MenuPrincipal();
        this.setVisible(false);
        mpe.setVisible(true);
    }//GEN-LAST:event_jLabelMenuPrincipal3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FProductos().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelClientes;
    private javax.swing.JLabel jLabelCloseSesion;
    private javax.swing.JLabel jLabelConfiguracion;
    private javax.swing.JLabel jLabelConsultar;
    private javax.swing.JLabel jLabelEditar;
    private javax.swing.JLabel jLabelEliminar;
    private javax.swing.JLabel jLabelEmpleados;
    private javax.swing.JLabel jLabelGuardar;
    private javax.swing.JLabel jLabelImprimir;
    private javax.swing.JLabel jLabelInsumos;
    private javax.swing.JLabel jLabelLimpiar;
    private javax.swing.JLabel jLabelMenuPrincipal3;
    private javax.swing.JLabel jLabelObras;
    private javax.swing.JLabel jLabelProductos;
    private javax.swing.JLabel jLabelProveedores;
    private javax.swing.JLabel jLabelUsuarios;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner spCantidad;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables
}
