/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mallas.interfaz;

import com.mallas.entidades.EntUsuario;
import com.mallas.negocio.UsuarioNegocio;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author samsung
 */
public class FUsuarios extends javax.swing.JFrame implements MouseListener, ActionListener, ItemListener {

    /**
     * Creates new form FUsuarios
     */
    UsuarioNegocio userN = new UsuarioNegocio();
    EntUsuario userE = new EntUsuario();

    public FUsuarios() throws Exception {
        initComponents();
        super.setLocationRelativeTo(null);
        super.setBackground(Color.white);
        jLabelGuardar.setOpaque(true);
        jLabelEditar.setOpaque(true);
        jLabelConsultar.setOpaque(true);
        jLabelEliminar.setOpaque(true);
        jLabelLimpiar.setOpaque(true);
        setIconImage(new ImageIcon(getClass().getResource("/com/mallas/imagenes/Desktop Icon.png")).getImage());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtClave = new javax.swing.JPasswordField();
        txtDNI = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cboPerfil = new javax.swing.JComboBox();
        txtCorreo = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cboEstado = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabelGuardar = new javax.swing.JLabel();
        jLabelEditar = new javax.swing.JLabel();
        jLabelConsultar = new javax.swing.JLabel();
        jLabelEliminar = new javax.swing.JLabel();
        jLabelLimpiar = new javax.swing.JLabel();
        jLabelImprimir = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabelInsumos5 = new javax.swing.JLabel();
        jLabelClientes3 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabelEmpleados3 = new javax.swing.JLabel();
        jLabelUsuarios3 = new javax.swing.JLabel();
        jLabelObras3 = new javax.swing.JLabel();
        jLabelProveedores3 = new javax.swing.JLabel();
        jLabelProductos3 = new javax.swing.JLabel();
        jLabelCloseSesion3 = new javax.swing.JLabel();
        jLabelSettings = new javax.swing.JLabel();
        jLabelMenuPrincipal3 = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Usuarios");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Gill Sans MT", 1, 12)); // NOI18N
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(40, 40, 40)));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("* Apellido:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Correo:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("* DNI:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("* Nombre:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("* Perfil:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("* Estado:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("* Clave:");

        cboPerfil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Administrador", "Empleado" }));

        txtCorreo.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("* Usuario:");

        cboEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Activo", "Inactivo" }));

        jPanel2.setBackground(new java.awt.Color(40, 40, 40));
        jPanel2.setPreferredSize(new java.awt.Dimension(500, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Administración de Usuarios");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap())
        );

        jLabelGuardar.setBackground(new java.awt.Color(8, 102, 198));
        jLabelGuardar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelGuardar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGuardar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelGuardar.setText("Guardar");
        jLabelGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelGuardar.setOpaque(true);
        jLabelGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelGuardarMouseClicked(evt);
            }
        });

        jLabelEditar.setBackground(new java.awt.Color(8, 102, 198));
        jLabelEditar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelEditar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEditar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEditar.setText("Actualizar");
        jLabelEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelEditar.setOpaque(true);
        jLabelEditar.setPreferredSize(new java.awt.Dimension(45, 16));
        jLabelEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelEditarMouseClicked(evt);
            }
        });

        jLabelConsultar.setBackground(new java.awt.Color(8, 102, 198));
        jLabelConsultar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelConsultar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelConsultar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelConsultar.setText("Consultar");
        jLabelConsultar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelConsultar.setOpaque(true);
        jLabelConsultar.setPreferredSize(new java.awt.Dimension(45, 16));
        jLabelConsultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelConsultarMouseClicked(evt);
            }
        });

        jLabelEliminar.setBackground(new java.awt.Color(8, 102, 198));
        jLabelEliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelEliminar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEliminar.setText("Eliminar");
        jLabelEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelEliminar.setOpaque(true);
        jLabelEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelEliminarMouseClicked(evt);
            }
        });

        jLabelLimpiar.setBackground(new java.awt.Color(8, 102, 198));
        jLabelLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLimpiar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLimpiar.setText("Limpiar");
        jLabelLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelLimpiar.setOpaque(true);
        jLabelLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLimpiarMouseClicked(evt);
            }
        });

        jLabelImprimir.setBackground(new java.awt.Color(8, 102, 198));
        jLabelImprimir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelImprimir.setForeground(new java.awt.Color(255, 255, 255));
        jLabelImprimir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelImprimir.setText("Imprimir");
        jLabelImprimir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelImprimir.setOpaque(true);
        jLabelImprimir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelImprimirMouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("El Correo no es un campo obligatorio, sin embargo es necesario para la recuperación de contraseña en caso de olvidarse");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 34, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(jLabel4))
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(14, 14, 14)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cboPerfil, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cboEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtClave, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(127, 127, 127))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtUsuario.getAccessibleContext().setAccessibleName("");

        jPanel4.setBackground(new java.awt.Color(8, 102, 198));
        jPanel4.setPreferredSize(new java.awt.Dimension(1024, 106));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mallas/imagenes/logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel10)
                .addContainerGap(847, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addContainerGap())
        );

        jPanel8.setBackground(new java.awt.Color(40, 40, 40));

        jLabelInsumos5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelInsumos5.setForeground(new java.awt.Color(204, 204, 204));
        jLabelInsumos5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelInsumos5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mallas/imagenes/InsumosIcon.png"))); // NOI18N
        jLabelInsumos5.setText("Insumos");
        jLabelInsumos5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jLabelInsumos5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelInsumos5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelInsumos5MouseClicked(evt);
            }
        });

        jLabelClientes3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelClientes3.setForeground(new java.awt.Color(204, 204, 204));
        jLabelClientes3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelClientes3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mallas/imagenes/ClientesIcon.png"))); // NOI18N
        jLabelClientes3.setText("Clientes");
        jLabelClientes3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jLabelClientes3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClientes3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelClientes3MouseClicked(evt);
            }
        });

        jLabel17.setBackground(new java.awt.Color(35, 35, 35));
        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Navegación");
        jLabel17.setOpaque(true);

        jLabelEmpleados3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelEmpleados3.setForeground(new java.awt.Color(204, 204, 204));
        jLabelEmpleados3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEmpleados3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mallas/imagenes/PersonalIcon.png"))); // NOI18N
        jLabelEmpleados3.setText("Empleados");
        jLabelEmpleados3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jLabelEmpleados3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelEmpleados3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelEmpleados3MouseClicked(evt);
            }
        });

        jLabelUsuarios3.setBackground(new java.awt.Color(51, 51, 51));
        jLabelUsuarios3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelUsuarios3.setForeground(new java.awt.Color(204, 204, 204));
        jLabelUsuarios3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelUsuarios3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mallas/imagenes/PersonalIcon.png"))); // NOI18N
        jLabelUsuarios3.setText("Usuarios");
        jLabelUsuarios3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jLabelUsuarios3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelUsuarios3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelUsuarios3MouseClicked(evt);
            }
        });

        jLabelObras3.setBackground(new java.awt.Color(51, 51, 51));
        jLabelObras3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelObras3.setForeground(new java.awt.Color(204, 204, 204));
        jLabelObras3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelObras3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mallas/imagenes/ObrasIcon.png"))); // NOI18N
        jLabelObras3.setText("Obras");
        jLabelObras3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jLabelObras3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelObras3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelObras3MouseClicked(evt);
            }
        });

        jLabelProveedores3.setBackground(new java.awt.Color(51, 51, 51));
        jLabelProveedores3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelProveedores3.setForeground(new java.awt.Color(204, 204, 204));
        jLabelProveedores3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProveedores3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mallas/imagenes/ProveedoresIcon.png"))); // NOI18N
        jLabelProveedores3.setText("Proveedores");
        jLabelProveedores3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jLabelProveedores3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelProveedores3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelProveedores3MouseClicked(evt);
            }
        });

        jLabelProductos3.setBackground(new java.awt.Color(51, 51, 51));
        jLabelProductos3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelProductos3.setForeground(new java.awt.Color(204, 204, 204));
        jLabelProductos3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProductos3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mallas/imagenes/ProductosIcon.png"))); // NOI18N
        jLabelProductos3.setText("Productos");
        jLabelProductos3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jLabelProductos3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelProductos3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelProductos3MouseClicked(evt);
            }
        });

        jLabelCloseSesion3.setBackground(new java.awt.Color(51, 51, 51));
        jLabelCloseSesion3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelCloseSesion3.setForeground(new java.awt.Color(204, 204, 204));
        jLabelCloseSesion3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCloseSesion3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mallas/imagenes/CerrarSesion.png"))); // NOI18N
        jLabelCloseSesion3.setText("Cerrar Sesión");
        jLabelCloseSesion3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jLabelCloseSesion3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelCloseSesion3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseSesion3MouseClicked(evt);
            }
        });

        jLabelSettings.setBackground(new java.awt.Color(51, 51, 51));
        jLabelSettings.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelSettings.setForeground(new java.awt.Color(204, 204, 204));
        jLabelSettings.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mallas/imagenes/SettingsIcon.png"))); // NOI18N
        jLabelSettings.setText("Configuración de cuenta");
        jLabelSettings.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jLabelSettings.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelSettings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSettingsMouseClicked(evt);
            }
        });

        jLabelMenuPrincipal3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelMenuPrincipal3.setForeground(new java.awt.Color(204, 204, 204));
        jLabelMenuPrincipal3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMenuPrincipal3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mallas/imagenes/Home.png"))); // NOI18N
        jLabelMenuPrincipal3.setText("Menú Principal");
        jLabelMenuPrincipal3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jLabelMenuPrincipal3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMenuPrincipal3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabelMenuPrincipal3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMenuPrincipal3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelInsumos5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelClientes3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelEmpleados3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelUsuarios3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelObras3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelProveedores3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelProductos3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelCloseSesion3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelSettings, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
            .addComponent(jLabelMenuPrincipal3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(jLabelMenuPrincipal3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelInsumos5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelClientes3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelEmpleados3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelUsuarios3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelObras3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelProveedores3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelProductos3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCloseSesion3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelGuardarMouseClicked

        if (txtUsuario.getText().trim().length() > 0) {
            userE.setUsuario(txtUsuario.getText());
        } else {
            JOptionPane.showMessageDialog(null, "Por favor ingrese el Nombre de Usuario", "Datos Faltantes", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (txtClave.getText().trim().length() > 0) {
            if (txtUsuario.getText().trim().equals(txtClave.getText().trim()) || txtDNI.getText().trim().equals(txtClave.getText().trim())
                    || txtNombre.getText().trim().equals(txtClave.getText().trim()) || txtApellido.getText().trim().equals(txtClave.getText().trim())) {
                JOptionPane.showMessageDialog(null, "La clave no puede ser igual al nombre de usuario, DNI, nombre ni apellido", "Datos Faltantes", JOptionPane.ERROR_MESSAGE);
                return;
            }else{
                userE.setClave(txtClave.getText());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Por favor ingrese la Clave", "Datos Faltantes", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (txtClave.getText().trim().length() < 10) {
            JOptionPane.showMessageDialog(null, "La Clave debe ser mayor de 10 caracteres", "Datos Incompletos", JOptionPane.ERROR_MESSAGE);
        }

        userE.setRol(cboPerfil.getSelectedItem().toString());

        userE.setEstado(cboEstado.getSelectedItem().toString());

        int dni = Integer.parseInt(txtDNI.getText());

        if (txtDNI.getText().trim().length() > 0) {
            userE.setDNI(dni);
        } else {
            JOptionPane.showMessageDialog(null, "Por favor ingrese el DNI", "Datos Faltantes", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (txtNombre.getText().trim().length() > 0) {
            userE.setNombre(txtNombre.getText());
        } else {
            JOptionPane.showMessageDialog(null, "Por favor ingrese el Nombre propio", "Datos Faltantes", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (txtApellido.getText().trim().length() > 0) {
            userE.setApellido(txtApellido.getText());
        } else {
            JOptionPane.showMessageDialog(null, "Por favor ingrese el Apellido", "Datos Faltantes", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (txtCorreo.getText().trim() != null) {
            userE.setCorreo(txtCorreo.getText());
        } else {
            userE.setCorreo("Sin correo");
        }

        boolean respuesta;

        try {
            respuesta = userN.guardarUsuario(userE);
            if (respuesta) {
                if (cboPerfil.getSelectedItem().equals("Administrador")) {
                    JOptionPane.showMessageDialog(null, "Se ha guardado satisfactoriamente un usuario en el sistema como Administrador", "Guardado", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, "Se ha guardado satisfactoriamente un usuario en el sistema como Empleado", "Guardado", JOptionPane.INFORMATION_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "El usuario ya existe", "Guardado", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            Logger.getLogger(FUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jLabelGuardarMouseClicked

    private void jLabelEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEditarMouseClicked
        try {
            if (txtClave.getText().trim().length() > 0) {
                userE.setClave(txtClave.getText());
            } else {
                JOptionPane.showMessageDialog(null, "Por favor ingrese la Clave", "Datos Faltantes", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (txtClave.getText().trim().length() < 10) {
                JOptionPane.showMessageDialog(null, "La Clave debe ser mayor de 10 caracteres", "Datos Incompletos", JOptionPane.ERROR_MESSAGE);
            }

            userE.setRol(cboPerfil.getSelectedItem().toString());
            userE.setEstado(cboEstado.getSelectedItem().toString());

            if (txtCorreo.getText().trim() != null) {
                userE.setCorreo(txtCorreo.getText());
            } else {
                userE.setCorreo("Sin correo");
            }

            boolean respuesta = userN.actualizarUsuarioEnt(userE);


            if (respuesta == true) {
                JOptionPane.showMessageDialog(null, "Se ha actualizado satisfactoriamente", "Actualizar", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Hubo un error en el proceso de actualización del usuario", "Actualizar", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            Logger.getLogger(FUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabelEditarMouseClicked

    private void jLabelConsultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelConsultarMouseClicked
        int dni = Integer.parseInt(JOptionPane.showInputDialog(this, "Por favor ingrese el documento de identidad del usuario", "Consultar", JOptionPane.INFORMATION_MESSAGE)); //Ventana para ingresar texto        
        userE = userN.consultarUsuarioEnt(dni);

        if (userE != null) {
            txtUsuario.setText(userE.getUsuario());
            txtClave.setText(userE.getClave());
            cboPerfil.setSelectedItem(userE.getRol());
            cboEstado.setSelectedItem(userE.getEstado());
            txtDNI.setText(Integer.toString(userE.getDNI()));
            txtNombre.setText(userE.getNombre());
            txtApellido.setText(userE.getApellido());
            txtCorreo.setText(userE.getCorreo());

            txtUsuario.setEnabled(false);
            txtDNI.setEnabled(false);
            txtNombre.setEnabled(false);
            txtApellido.setEnabled(false);

        } else {
            JOptionPane.showMessageDialog(this, "El usuario no se ha encontrado", "Consultar", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jLabelConsultarMouseClicked

    private void jLabelEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEliminarMouseClicked
        int dni = Integer.parseInt(JOptionPane.showInputDialog(this, "Por favor ingrese el documento de identidad del usuario a eliminar", "Eliminar", JOptionPane.INFORMATION_MESSAGE)); //Ventana para ingresar texto

        try {
            if (userN.eliminarUsuarioEnt(dni)) {
                JOptionPane.showMessageDialog(this, "El usuario ha sido eliminado", "Eliminar", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "El usuario no se ha encontrado", "Eliminar", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            Logger.getLogger(FUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabelEliminarMouseClicked

    private void jLabelLimpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLimpiarMouseClicked
        txtUsuario.setText("");
        txtClave.setText("");
        txtNombre.setText("");
        txtApellido.setText("");
        txtCorreo.setText("");
        txtDNI.setText("");

        txtUsuario.setEnabled(true);
        txtDNI.setEnabled(true);
        txtNombre.setEnabled(true);
        txtApellido.setEnabled(true);
    }//GEN-LAST:event_jLabelLimpiarMouseClicked

    private void jLabelImprimirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelImprimirMouseClicked
        userN.imprimirLista();
    }//GEN-LAST:event_jLabelImprimirMouseClicked

    private void jLabelInsumos5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelInsumos5MouseClicked
        FInsumos fIns = new FInsumos();
        this.setVisible(false);
        fIns.setVisible(true);
    }//GEN-LAST:event_jLabelInsumos5MouseClicked

    private void jLabelClientes3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelClientes3MouseClicked
        FClientes fCli = new FClientes();
        this.setVisible(false);
        fCli.setVisible(true);
    }//GEN-LAST:event_jLabelClientes3MouseClicked

    private void jLabelEmpleados3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEmpleados3MouseClicked
        FEmpleados fEmpl = new FEmpleados();
        this.setVisible(false);
        fEmpl.setVisible(true);
    }//GEN-LAST:event_jLabelEmpleados3MouseClicked

    private void jLabelUsuarios3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelUsuarios3MouseClicked
        try {
            FUsuarios fUsu = new FUsuarios();
            this.setVisible(false);
            fUsu.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(FUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabelUsuarios3MouseClicked

    private void jLabelObras3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelObras3MouseClicked
        FObras fObr = new FObras();
        this.setVisible(false);
        fObr.setVisible(true);
    }//GEN-LAST:event_jLabelObras3MouseClicked

    private void jLabelProveedores3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelProveedores3MouseClicked
        FProveedores fProv = new FProveedores();
        this.setVisible(false);
        fProv.setVisible(true);
    }//GEN-LAST:event_jLabelProveedores3MouseClicked

    private void jLabelProductos3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelProductos3MouseClicked
        FProductos fPro = new FProductos();
        this.setVisible(false);
        fPro.setVisible(true);
    }//GEN-LAST:event_jLabelProductos3MouseClicked

    private void jLabelCloseSesion3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseSesion3MouseClicked
        int confirmar = JOptionPane.showConfirmDialog(null, "¿Está seguro que desea cerrar la sesión?", "Salir", JOptionPane.YES_NO_OPTION);

        if (JOptionPane.YES_OPTION == confirmar) {
            try {
                InicioSesion is = new InicioSesion();
                this.dispose();
                is.setVisible(true);
            } catch (Exception ex) {
                Logger.getLogger(FUsuarios.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jLabelCloseSesion3MouseClicked

    private void jLabelSettingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSettingsMouseClicked
        try {
            ConfiguracionCuenta cc = new ConfiguracionCuenta();
            this.setVisible(false);
            cc.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(ConfiguracionCuenta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabelSettingsMouseClicked

    private void jLabelMenuPrincipal3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMenuPrincipal3MouseClicked
        MenuPrincipal mpe = new MenuPrincipal();
        this.setVisible(false);
        mpe.setVisible(true);
    }//GEN-LAST:event_jLabelMenuPrincipal3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FUsuarios().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(FUsuarios.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cboEstado;
    private javax.swing.JComboBox cboPerfil;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelClientes3;
    private javax.swing.JLabel jLabelCloseSesion3;
    private javax.swing.JLabel jLabelConsultar;
    private javax.swing.JLabel jLabelEditar;
    private javax.swing.JLabel jLabelEliminar;
    private javax.swing.JLabel jLabelEmpleados3;
    private javax.swing.JLabel jLabelGuardar;
    private javax.swing.JLabel jLabelImprimir;
    private javax.swing.JLabel jLabelInsumos5;
    private javax.swing.JLabel jLabelLimpiar;
    private javax.swing.JLabel jLabelMenuPrincipal3;
    private javax.swing.JLabel jLabelObras3;
    private javax.swing.JLabel jLabelProductos3;
    private javax.swing.JLabel jLabelProveedores3;
    private javax.swing.JLabel jLabelSettings;
    private javax.swing.JLabel jLabelUsuarios3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JPasswordField txtClave;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mouseClicked(MouseEvent e) {
    }

    @Override
    public void mousePressed(MouseEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseReleased(MouseEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseEntered(MouseEvent e) {
    }

    @Override
    public void mouseExited(MouseEvent e) {
    }

    @Override
    public void actionPerformed(ActionEvent e) {
    }

    @Override
    public void itemStateChanged(ItemEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
