/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mallas.interfaz;

import java.awt.Color;
import java.awt.Component;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author samsung
 */
public class MenuPrincipalE extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    Border border;

    public MenuPrincipalE() {
        initComponents();
        super.setLocationRelativeTo(null);
        border = BorderFactory.createLineBorder(Color.GRAY, 3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabelMenuPrincipal3 = new javax.swing.JLabel();
        jLabelInsumos3 = new javax.swing.JLabel();
        jLabelClientes3 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabelObras3 = new javax.swing.JLabel();
        jLabelProveedores3 = new javax.swing.JLabel();
        jLabelProductos3 = new javax.swing.JLabel();
        jLabelCloseSesion3 = new javax.swing.JLabel();
        jLabelSettings = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        Home = new javax.swing.JLabel();
        Bienvenida = new javax.swing.JLabel();
        Insumos = new javax.swing.JLabel();
        Obras = new javax.swing.JLabel();
        Proveedores = new javax.swing.JLabel();
        Clientes = new javax.swing.JLabel();
        Productos = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel7.setBackground(new java.awt.Color(8, 102, 198));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mallas/imagenes/logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel10)
                .addContainerGap(847, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(40, 40, 40));

        jLabelMenuPrincipal3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelMenuPrincipal3.setForeground(new java.awt.Color(204, 204, 204));
        jLabelMenuPrincipal3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMenuPrincipal3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mallas/imagenes/Home.png"))); // NOI18N
        jLabelMenuPrincipal3.setText("Menú Principal");
        jLabelMenuPrincipal3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jLabelMenuPrincipal3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMenuPrincipal3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabelMenuPrincipal3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMenuPrincipal3MouseClicked(evt);
            }
        });

        jLabelInsumos3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelInsumos3.setForeground(new java.awt.Color(204, 204, 204));
        jLabelInsumos3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelInsumos3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mallas/imagenes/InsumosIcon.png"))); // NOI18N
        jLabelInsumos3.setText("Insumos");
        jLabelInsumos3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jLabelInsumos3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelInsumos3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelInsumos3MouseClicked(evt);
            }
        });

        jLabelClientes3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelClientes3.setForeground(new java.awt.Color(204, 204, 204));
        jLabelClientes3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelClientes3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mallas/imagenes/ClientesIcon.png"))); // NOI18N
        jLabelClientes3.setText("Clientes");
        jLabelClientes3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jLabelClientes3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClientes3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelClientes3MouseClicked(evt);
            }
        });

        jLabel17.setBackground(new java.awt.Color(35, 35, 35));
        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Navegación");
        jLabel17.setOpaque(true);

        jLabelObras3.setBackground(new java.awt.Color(51, 51, 51));
        jLabelObras3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelObras3.setForeground(new java.awt.Color(204, 204, 204));
        jLabelObras3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelObras3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mallas/imagenes/ObrasIcon.png"))); // NOI18N
        jLabelObras3.setText("Obras");
        jLabelObras3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jLabelObras3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelObras3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelObras3MouseClicked(evt);
            }
        });

        jLabelProveedores3.setBackground(new java.awt.Color(51, 51, 51));
        jLabelProveedores3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelProveedores3.setForeground(new java.awt.Color(204, 204, 204));
        jLabelProveedores3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProveedores3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mallas/imagenes/ProveedoresIcon.png"))); // NOI18N
        jLabelProveedores3.setText("Proveedores");
        jLabelProveedores3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jLabelProveedores3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelProveedores3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelProveedores3MouseClicked(evt);
            }
        });

        jLabelProductos3.setBackground(new java.awt.Color(51, 51, 51));
        jLabelProductos3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelProductos3.setForeground(new java.awt.Color(204, 204, 204));
        jLabelProductos3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProductos3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mallas/imagenes/ProductosIcon.png"))); // NOI18N
        jLabelProductos3.setText("Productos");
        jLabelProductos3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jLabelProductos3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelProductos3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelProductos3MouseClicked(evt);
            }
        });

        jLabelCloseSesion3.setBackground(new java.awt.Color(51, 51, 51));
        jLabelCloseSesion3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelCloseSesion3.setForeground(new java.awt.Color(204, 204, 204));
        jLabelCloseSesion3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCloseSesion3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mallas/imagenes/CerrarSesion.png"))); // NOI18N
        jLabelCloseSesion3.setText("Cerrar Sesión");
        jLabelCloseSesion3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jLabelCloseSesion3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelCloseSesion3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseSesion3MouseClicked(evt);
            }
        });

        jLabelSettings.setBackground(new java.awt.Color(51, 51, 51));
        jLabelSettings.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelSettings.setForeground(new java.awt.Color(204, 204, 204));
        jLabelSettings.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mallas/imagenes/SettingsIcon.png"))); // NOI18N
        jLabelSettings.setText("Configuración de cuenta");
        jLabelSettings.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jLabelSettings.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelSettings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSettingsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelInsumos3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelObras3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelProveedores3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelProductos3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelMenuPrincipal3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelSettings, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
            .addComponent(jLabelCloseSesion3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelClientes3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(jLabelMenuPrincipal3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelInsumos3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelClientes3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelObras3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelProveedores3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelProductos3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCloseSesion3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(40, 40, 40)));

        jPanel2.setBackground(new java.awt.Color(40, 40, 40));
        jPanel2.setPreferredSize(new java.awt.Dimension(500, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Panel de Administración");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(591, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap())
        );

        Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mallas/imagenes/Principal.png"))); // NOI18N

        Bienvenida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mallas/imagenes/Bienvenida.png"))); // NOI18N

        Insumos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mallas/imagenes/Insumos.png"))); // NOI18N
        Insumos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Insumos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InsumosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                InsumosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                InsumosMouseExited(evt);
            }
        });

        Obras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mallas/imagenes/Obras.png"))); // NOI18N
        Obras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Obras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ObrasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ObrasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ObrasMouseExited(evt);
            }
        });

        Proveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mallas/imagenes/Proveedores.png"))); // NOI18N
        Proveedores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Proveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProveedoresMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ProveedoresMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ProveedoresMouseExited(evt);
            }
        });

        Clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mallas/imagenes/Clientes.png"))); // NOI18N
        Clientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClientesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ClientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ClientesMouseExited(evt);
            }
        });

        Productos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mallas/imagenes/Productos.png"))); // NOI18N
        Productos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Productos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ProductosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ProductosMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("PÁGINAS DE ACCESO RÁPIDO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Home)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Insumos, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Obras, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Proveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Productos, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addComponent(Bienvenida))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Home)
                    .addComponent(Bienvenida))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Insumos, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Obras, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Proveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Productos, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 11, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelInsumos3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelInsumos3MouseClicked
        FInsumosE fIns = new FInsumosE();
        this.setVisible(false);
        fIns.setVisible(true);
    }//GEN-LAST:event_jLabelInsumos3MouseClicked

    private void jLabelClientes3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelClientes3MouseClicked
        FClientesE fCli = new FClientesE();
        this.setVisible(false);
        fCli.setVisible(true);
    }//GEN-LAST:event_jLabelClientes3MouseClicked

    private void jLabelObras3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelObras3MouseClicked
        FObrasE fObr = new FObrasE();
        this.setVisible(false);
        fObr.setVisible(true);
    }//GEN-LAST:event_jLabelObras3MouseClicked

    private void jLabelProveedores3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelProveedores3MouseClicked
        FProveedoresE fProv = new FProveedoresE();
        this.setVisible(false);
        fProv.setVisible(true);
    }//GEN-LAST:event_jLabelProveedores3MouseClicked

    private void jLabelProductos3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelProductos3MouseClicked
        FProductosE fPro = new FProductosE();
        this.setVisible(false);
        fPro.setVisible(true);
    }//GEN-LAST:event_jLabelProductos3MouseClicked

    private void jLabelCloseSesion3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseSesion3MouseClicked
        int confirmar = JOptionPane.showConfirmDialog(null, "¿Está seguro que desea cerrar la sesión?", "Salir", JOptionPane.YES_NO_OPTION);

        if (JOptionPane.YES_OPTION == confirmar) {
            try {
                InicioSesion is = new InicioSesion();
                this.dispose();
                is.setVisible(true);
            } catch (Exception ex) {
                Logger.getLogger(FUsuarios.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jLabelCloseSesion3MouseClicked

    private void jLabelSettingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSettingsMouseClicked
        try {
            ConfiguracionCuentaE cc = new ConfiguracionCuentaE();
            this.setVisible(false);
            cc.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(ConfiguracionCuenta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabelSettingsMouseClicked

    private void InsumosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InsumosMouseClicked
        FInsumosE fIns = new FInsumosE();
        this.setVisible(false);
        fIns.setVisible(true);
    }//GEN-LAST:event_InsumosMouseClicked

    private void ObrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ObrasMouseClicked
        FObrasE fObr = new FObrasE();
        this.setVisible(false);
        fObr.setVisible(true);
    }//GEN-LAST:event_ObrasMouseClicked

    private void ProveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProveedoresMouseClicked
        FProveedoresE fProv = new FProveedoresE();
        this.setVisible(false);
        fProv.setVisible(true);
    }//GEN-LAST:event_ProveedoresMouseClicked

    private void ClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClientesMouseClicked
        FClientesE fCli = new FClientesE();
        this.setVisible(false);
        fCli.setVisible(true);
    }//GEN-LAST:event_ClientesMouseClicked

    private void ProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductosMouseClicked
        FProductosE fPro = new FProductosE();
        this.setVisible(false);
        fPro.setVisible(true);
    }//GEN-LAST:event_ProductosMouseClicked

    private void InsumosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InsumosMouseEntered
        Insumos.setBorder(border);
    }//GEN-LAST:event_InsumosMouseEntered

    private void ObrasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ObrasMouseEntered
       Obras.setBorder(border);
    }//GEN-LAST:event_ObrasMouseEntered

    private void ProveedoresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProveedoresMouseEntered
        Proveedores.setBorder(border);
    }//GEN-LAST:event_ProveedoresMouseEntered

    private void ClientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClientesMouseEntered
        Clientes.setBorder(border);
    }//GEN-LAST:event_ClientesMouseEntered

    private void ProductosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductosMouseEntered
        Productos.setBorder(border);
    }//GEN-LAST:event_ProductosMouseEntered

    private void InsumosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InsumosMouseExited
        Insumos.setBorder(new EmptyBorder(0,0,0,0));
    }//GEN-LAST:event_InsumosMouseExited

    private void ObrasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ObrasMouseExited
        Obras.setBorder(new EmptyBorder(0,0,0,0));
    }//GEN-LAST:event_ObrasMouseExited

    private void ProveedoresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProveedoresMouseExited
        Proveedores.setBorder(new EmptyBorder(0,0,0,0));
    }//GEN-LAST:event_ProveedoresMouseExited

    private void ClientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClientesMouseExited
        Clientes.setBorder(new EmptyBorder(0,0,0,0));
    }//GEN-LAST:event_ClientesMouseExited

    private void ProductosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductosMouseExited
        Productos.setBorder(new EmptyBorder(0,0,0,0));
    }//GEN-LAST:event_ProductosMouseExited

    private void jLabelMenuPrincipal3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMenuPrincipal3MouseClicked
        MenuPrincipalE mpe = new MenuPrincipalE();
        this.setVisible(false);
        mpe.setVisible(true);
    }//GEN-LAST:event_jLabelMenuPrincipal3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipalE().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bienvenida;
    private javax.swing.JLabel Clientes;
    private javax.swing.JLabel Home;
    private javax.swing.JLabel Insumos;
    private javax.swing.JLabel Obras;
    private javax.swing.JLabel Productos;
    private javax.swing.JLabel Proveedores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelClientes3;
    private javax.swing.JLabel jLabelCloseSesion3;
    private javax.swing.JLabel jLabelInsumos3;
    private javax.swing.JLabel jLabelMenuPrincipal3;
    private javax.swing.JLabel jLabelObras3;
    private javax.swing.JLabel jLabelProductos3;
    private javax.swing.JLabel jLabelProveedores3;
    private javax.swing.JLabel jLabelSettings;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    // End of variables declaration//GEN-END:variables
}
